name: Build and release
run-name: "Build version ${{ inputs.version_tag }} and make a release"

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Tag to build the release from'
        required: true
        type: string

jobs:
  build-and-release:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{inputs.version_tag}}
      - name: Setup environment
        uses: ./.github/actions/setup_poetry_env.yaml
      - name: Build package
        run: poetry build
      - name: Save artifacts to cache
        uses: actions/cache/save@v3
        with:
          path: ./dist
          key: ${{ inputs.version_tag }}-buildartifacts
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          export VERSION=$(poetry version -s)
          hub release create -d $([[ $VERSION =~ ^[[:digit:]]*(\.[[:digit:]]*)?(\.[[:digit:]]*)?$ ]] || echo "-p") -a ./dist/*  ${{inputs.version_tag}}
        shell: bash

