name: Build and release
on:
  workflow_call:
    inputs:
      VERSION_TAG:
        description: 'Tag to build the release from'
        required: true
        type: string

jobs:
  build-and-release:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Requirements
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          export VERSION=$(poetry version -s)
          hub release create -d $([[ $VERSION =~ ^[[:digit:]]*(\.[[:digit:]]*)?(\.[[:digit:]]*)?$ ]] || echo "-p") -a ./dist/*  ${{VERSION_TAG}}
        shell: bash

