name: Make a new version and tag
on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Version (PEP 440 compliant)'
        required: true
        type: string

env:
  VERSION_TAG: v${{inputs.VERSION}}

jobs:
  set-poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Tag as Package Version
        run: |
          sed -i -r 's/__version__ *= *".*"/__version__ = "${{ env.VERSION_TAG }}"/g' ./openmnglab/__init__.py
          sed -i '0,/version =.*/s//version = "'"${{ env.VERSION_TAG}}"'"/' ./pyproject.toml
        shell: bash
      - name: Add and Commit Version
        run: |
          git add openmnglab/__init__.py ./pyproject.toml
          git config --global user.name "Poetry Versioning Bot"
          git config --global user.email "versioningbot@digital-c-fiber.invalid"
          git commit -m "Change version to ${{ env.VERSION_TAG }}" --allow-empty
          git tag ${{env.VERSION_TAG}}
          git push origin HEAD:main
          git push origin ${{env.VERSION_TAG}}
        shell: bash


