name: "Make a release"
run-name: "Release tag ${{ github.ref_name }}"

on:
  push:
    tags:
      - 'v*'

jobs:
  verify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check that trigger is protected
        if: !${{ github.ref_protected }}
        uses: actions/github-script@v3
        with:
          script: "core.setFailed('automation safeguard tripped: workflow was triggered by ${{ github.ref }}, which is not protected')"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup_poetry_env.yaml
        with:
          install-deps: false
      - id: package_version
        run: echo "ver=v$(poetry version -s)" >> $GITHUB_OUTPUT
      - name: Check that package version matches tag version
        if: ${{steps.package_version.outputs.new_version}} != ${{github.ref_name}}
        uses: actions/github-script@v3
        with:
          script: "core.setFailed('automation safeguard tripped: package version ${{steps.package_version.outputs.ver}} does not match pushed tag ${{github.ref_name}}')"
  build-and-release:
    needs: verify-release
    uses: ./.github/workflows/build_release.yaml
    with:
      version_tag: ${{github.ref_name}}

