name: "Publish release to PyPI"
run-name: "Publish ${{ github.ref }} to PyPI"

on:
  release:
    types: [ published ]

jobs:
  pypi-publish:
    name: "Upload release to pypi"
    runs-on: ubuntu-latest
    environment:
      name: pypi-publish
      url: https://pypi.org/p/openmnglab/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download release files
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir dist
          cd dist
          hub release download ${{ github.ref }}
      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1

